# Working directory
# . or absolute path, please note that the directories following must be under root.
root = "."
tmp_dir = ".air"

[build]
cmd = "go build -tags=debug -o ./.build/start ./cmd/start"
bin = "./.build/start"
include_ext = ["go", "tpl", "tmpl", "html"]
exclude_dir = ["src", "node_modules"]
exclude_regex = ["_test\\.go"]
exclude_unchanged = true
follow_symlink = true
stop_on_error = true
send_interrupt = false
log = "air.log"

[log]
# Show log time
time = false
# Only show main log (silences watcher, build, runner)
main_only = false
# silence all logs produced by air
silent = false

[misc]
clean_on_exit = true

[screen]
clear_on_rebuild = true
keep_scroll = true
