services:
  db:
    image: postgres:17
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: local
      POSTGRES_USER: local
      POSTGRES_DB: local
    ports:
      - "5432:5432"
    networks:
      - intertiaframe

networks:
  intertiaframe:
    name: local-intertiaframe-network
